### ISSUE TITLE
Non trial release to CPAN?

### ISSUE THREAD

**Issue by kablamo** [ka2u/Net-Amazon-DynamoDB-Lite#1]
This looks really good.  How about a non trial release to CPAN?  I can't install trial releases with carton.

**Comment by ka2u** [comment]
If our product with this was released, I thought I released a non trial. However this is already stable. I'll release non trial soon.

**Comment by ka2u** [comment]
I released non trial v0.03. Please use it by all means!

**Comment by kablamo** [comment]
:tada: Thanks!
